# -*- coding: utf-8 -*-
"""dashboard_visualisasi_analisis_ecommers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-PR0e30FUbeL8IXgMRLy8P9z95c5VXDD
"""

import pandas as pd
import streamlit as st
import seaborn as sns
import matplotlib.pyplot as plt

# Load data
all_df = pd.read_csv('https://raw.githubusercontent.com/RioFebriyan244/Project_Analisis_Data_Ecommers/refs/heads/main/dashboard/all_data_ecommers.csv')
all_df["order_date"] = pd.to_datetime(all_df["order_date"])

# Tanggal min dan max dari dataset
min_date = all_df["order_date"].min()
max_date = all_df["order_date"].max()

# Widget pilih rentang tanggal
start_date, end_date = st.date_input(
    "Pilih rentang tanggal:",
    [min_date, max_date],
    min_value=min_date,
    max_value=max_date
)

# Filter data berdasarkan tanggal yang dipilih
filtered_df = all_df[(all_df["order_date"] >= pd.to_datetime(start_date)) & (all_df["order_date"] <= pd.to_datetime(end_date))]

# Buat monthly summary
monthly_orders_df = filtered_df.resample(rule='M', on='order_date').agg({
    "order_id": "nunique",
    "total_price": "sum"
})
monthly_orders_df.index = monthly_orders_df.index.strftime('%B')
monthly_orders_df = monthly_orders_df.reset_index()
monthly_orders_df.rename(columns={
    "order_date": "month",
    "order_id": "order_count",
    "total_price": "revenue"
}, inplace=True)

# Judul halaman
st.title("Number of Orders and Revenue per Month (2021)")

# Plot
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(
    monthly_orders_df["month"],
    monthly_orders_df["order_count"],
    marker='o',
    linewidth=2,
    color="#72BCD4"
)
ax.set_title("Total Pesanan Per Bulan (2021)", loc="center", fontsize=20)
ax.tick_params(axis='x', labelsize=10)
ax.tick_params(axis='y', labelsize=10)

# Tampilkan plot di Streamlit
st.pyplot(fig)

# --- Grafik 2: Revenue per Bulan ---
st.subheader("Total Revenue per Bulan (AUD)")
fig2, ax2 = plt.subplots(figsize=(10, 5))
ax2.plot(
    monthly_orders_df["month"],
    monthly_orders_df["revenue"],
    marker='o',
    linewidth=2,
    color="#72BCD4"
)
ax2.set_title("Total Revenue Per Bulan (2021)", loc="center", fontsize=20)
ax2.tick_params(axis='x', labelsize=10)
ax2.tick_params(axis='y', labelsize=10)
st.pyplot(fig2)

# ==================== Produk Terbaik & Terburuk ====================
# Agregasi jumlah quantity per produk
sum_order_items_df = filtered_df.groupby("product_name").agg({
    "quantity_x": "sum"
}).reset_index().sort_values(by="quantity_x", ascending=False)

st.subheader("Produk Terbaik dan Terburuk Berdasarkan Jumlah Penjualan")

fig3, ax = plt.subplots(nrows=1, ncols=2, figsize=(24, 6))
colors = ["#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3"]

# Best Performing
sns.barplot(
    x="quantity_x",
    y="product_name",
    data=sum_order_items_df.head(5),
    palette=colors,
    ax=ax[0]
)
ax[0].set_ylabel(None)
ax[0].set_xlabel(None)
ax[0].set_title("Best Performing Product", loc="center", fontsize=18)
ax[0].tick_params(axis='y', labelsize=15)

# Worst Performing
sns.barplot(
    x="quantity_x",
    y="product_name",
    data=sum_order_items_df.sort_values(by="quantity_x", ascending=True).head(5),
    palette=colors,
    ax=ax[1]
)
ax[1].set_ylabel(None)
ax[1].set_xlabel(None)
ax[1].invert_xaxis()
ax[1].yaxis.set_label_position("right")
ax[1].yaxis.tick_right()
ax[1].set_title("Worst Performing Product", loc="center", fontsize=18)
ax[1].tick_params(axis='y', labelsize=15)

plt.suptitle("Best and Worst Performing Product by Number of Sales", fontsize=20)
st.pyplot(fig3)