# -*- coding: utf-8 -*-
"""dashboard_visualisasi_analisis_ecommers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-PR0e30FUbeL8IXgMRLy8P9z95c5VXDD

**Membuat diagram batang / Bar Char untuk Dataset All_df dengan data gender**
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load data (gantilah ini dengan sumber data yang sesuai)
all_df = pd.read_csv("https://raw.githubusercontent.com/RioFebriyan244/Project_Analisis_Data_Ecommers/refs/heads/main/dashboard/all_data_ecommers.csv")

bygender_df = all_df.groupby(by="gender").customer_id.nunique().reset_index()
bygender_df.rename(columns={
    "customer_id" : "customer_count"
}, inplace=True)

# Warna untuk visualisasi
colors = sns.color_palette("pastel")

# Judul Aplikasi Streamlit
st.title("Customer Distribution by Gender")

# Membuat visualisasi dengan Matplotlib
fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(
    y="customer_count",
    x="gender",
    data=bygender_df.sort_values(by="customer_count", ascending=False),
    hue="gender",  # Tambahkan hue
    palette=colors,
    legend=False  # Opsional, jika tidak butuh legenda
)
ax.set_title("Number of Customers by Gender", fontsize=15)
ax.set_ylabel("")
ax.set_xlabel("")
ax.tick_params(axis='x', labelsize=12)

# Menampilkan plot di Streamlit
st.pyplot(fig)

"""**Membuat Pie Chart Menggunakan Dataset All_df dengan data Gender**"""

# Piechart Berdasarkan Gender

# Warna untuk visualisasi
colors = ['pink', 'yellow', 'red']
explode = (0.1, 0, 0)  # Melembungkan bagian pertama

# Judul Aplikasi Streamlit
st.title("Customer Distribution by Gender")

# Membuat visualisasi pie chart
fig, ax = plt.subplots(figsize=(6, 6))
ax.pie(
    bygender_df['customer_count'],
    labels=bygender_df['gender'],
    colors=colors,
    explode=explode,
    autopct='%1.1f%%',
    startangle=140,
    shadow=True
)
ax.set_title("Number of Customers by Gender")

# Menampilkan plot di Streamlit
st.pyplot(fig)

"""**Membuat Diagram Batang / Bar Chart Dengan Dataset All_df Menggunakan Data Kelompok Usia**"""

# Load data (gantilah ini dengan sumber data yang sesuai)
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#Berdasarkan Kelompok Usia
all_df = pd.read_csv("https://raw.githubusercontent.com/RioFebriyan244/Project_Analisis_Data_Ecommers/refs/heads/main/dashboard/all_data_ecommers.csv")
byage_df = all_df.groupby(by="age_group").customer_id.nunique().reset_index()
byage_df.rename(columns={
    "customer_id" : "customer_count"
}, inplace=True)

byage_df['age_group'] = pd.Categorical(byage_df['age_group'], ["Youth", "Adults", "Seniors"])

# Warna untuk visualisasi
colors_ = ["#D3D3D3", "#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3"]

# Judul Aplikasi Streamlit
st.title("Customer Distribution by Age Group")

# Membuat visualisasi dengan Matplotlib
fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(
    y="customer_count",
    x="age_group",
    data=byage_df.sort_values(by="age_group", ascending=False),
    palette=colors_,
    ax=ax
)
ax.set_title("Number of Customers by Age", fontsize=15)
ax.set_ylabel("")
ax.set_xlabel("")
ax.tick_params(axis='x', labelsize=12)

# Menampilkan plot di Streamlit
st.pyplot(fig)

# Load data (gantilah ini dengan sumber data yang sesuai)


# Warna untuk visualisasi
colors_bar = ["#D3D3D3", "#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3"]

# Judul Aplikasi Streamlit
st.title("Customer Distribution by Age")
# Data untuk pie chart
data_pie = {
    "age_group": ["18-24", "25-34", "35-44"],
    "size": [60, 30, 10]
}
byage_pie_df = pd.DataFrame(data_pie)
colors_pie = ['#72BCD4', '#D3D3D3', '#D3D3D3']
explode = (0.1, 0, 0)

# Membuat visualisasi pie chart
fig_pie, ax_pie = plt.subplots(figsize=(6, 6))
ax_pie.pie(
    byage_pie_df['size'],
    labels=byage_pie_df['age_group'],
    colors=colors_pie,
    explode=explode,
    autopct='%1.1f%%',
    startangle=140,
    shadow=True
)
ax_pie.set_title("Distribusi Usia")

# Menampilkan pie chart di Streamlit
st.pyplot(fig_pie)